### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by ronilbhatia** [aghlichl/KELP#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* Home page looks good! Make sure to add in your other wiki pages here in the same format, and add a link to your live site once you've pushed to Heroku.
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes 2-3 detail bullets for each of 4 app specific MVPs:
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
* Take a look at the Bluebird MVP list and format similarly. Time estimates should just be in parentheses next to MVPs, each MVP should be bolded, and should have 2-3 bullet points explaining in detail what each MVP will have (suggestions for these bullets are Adequate styling, adequate seeds, and smooth, bug-free navigations).
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* table names should be bolded, lowercase, and plural (make them headers -> add a couple #s before them)
* `num_useful`, `num_cool`, and `num_funny` shouldn't be attributes for `reviews`. You probably don't need these (they can be bonus features you work on later), but if you were to really implement them you would need to make a joins table for each of these so that you don't allow the same user to call a review useful or cool multiple times. But again this is far from a necessary feature and something I think you should not worry about in the 10 days for this project.
* review body should probably be datatype `text` instead of `string`
* don't need `photos` in your `reviews` table - you'll use a Rails ActiveStorage association in your `Review` model and AWS to host the associated images. I would also say that having photos for reviews might also be something to add in later. It's more important that the business itself have photos, so I would have the association there. Later (after the 10 days) you can work in adding photos for reviews as well.
* Don't need `avg_rating` in your `businesses` table. Instead this should be a method in the `Business` model that calculates the average rating from all the associated reviews.

---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* Good job on the state shape! Overall it looks good and I think you have pretty much everything that you need in here. Since this is javascript variable names should be in camelCase instead of snake_case, but I'm not going to force you to change it.
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* CRUD for businesses? I think you could have `PATCH` and `DELETE` routes for businesses as well.
* You need `GET` routes for reviews. You'll probably want a nested index route, like `/api/businesses/:business_id/reviews` so that you can get all reviews for a given business.
* All of your current routes for `Reviews` are superfluous and don't need to be nested (other than the index route I mentioned in the previous bullet). You should `POST`, `PATCH`, and `DELETE` directly to `/api/businesses` and `/api/businesses/:id`. We can discuss this when we meet, but you can also see the reading linked above on superfluous routes.
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
* Add `/businesses` route for searching by category or city.
* Seems like there aren't too many routes here, but as I think about it it does seem like most of what you need. I think you might also want a route for somebody to create a new review. Right now you have it right on the business page itself, but on Yelp's actual site creating a new review takes you to a new page. So you'll probably want a frontend route similar to `/reviews/new` or `/businesses/:businessId/reviews/new`. Either one would work and we can talk about what you might need to do differently depending on which route you choose. You'll also need a route to edit a review after it's been posted.

**Comment by aghlichl** [comment]
should be fine now. If you could take a look thanks.

**Comment by ronilbhatia** [comment]
Awesome - closed.
